import { buildTranslatePreservePrompt } from "../settings/normalize";
import type { Workflow } from "../shared/types";

export const WORKFLOWS: Workflow[] = [
	{
		id: "study-summary",
		commandId: "workflow-study-summary",
		name: "Study Summary",
		shortName: "Summarise",
		description: "Study guide",
		icon: "book-open",
		accent: "blue",
		prompt: [
			"Goal: Turn the provided note or selection into a useful study summary.",
			"",
			"Success criteria:",
			"- Capture the main idea in a short opening summary.",
			"- Group important points by topic or sequence.",
			"- Include key terms, claims, numbers, examples, and quotes only when present in the context.",
			"- End with the takeaways worth remembering.",
			"",
			"Constraints: Use only the note context. If evidence is missing or unclear, say what is missing.",
			"",
			"Output: Use concise Obsidian Markdown with headings and bullets."
		].join("\n")
	},
	{
		id: "action-plan",
		commandId: "workflow-action-plan",
		name: "Action Plan",
		shortName: "Plan",
		description: "Next steps",
		icon: "list-checks",
		accent: "green",
		prompt: [
			"Goal: Convert the note context into a practical action plan.",
			"",
			"Success criteria:",
			"- Identify the outcome the note points toward.",
			"- List concrete next actions in priority order.",
			"- Include owners, deadlines, tools, costs, dependencies, or constraints only when the context supports them.",
			"- Call out risks, blockers, open questions, and decisions needed.",
			"",
			"Constraints: Do not invent missing details. Mark assumptions clearly and keep recommendations tied to the note.",
			"",
			"Output: Use Obsidian Markdown with sections for Next actions, Risks, Open questions, and First step."
		].join("\n")
	},
	{
		id: "explain-simply",
		commandId: "workflow-explain-simply",
		name: "Explain Simply",
		shortName: "Explain",
		description: "Plain English",
		icon: "sparkles",
		accent: "violet",
		prompt: [
			"Goal: Explain the note context in simple, clear language without losing the important meaning.",
			"",
			"Success criteria:",
			"- Start with the core idea in plain English.",
			"- Define jargon and complex ideas using simple wording.",
			"- Use one short example or analogy when it helps and is consistent with the context.",
			"- Separate what the note says from any uncertainty or missing evidence.",
			"",
			"Constraints: Stay grounded in the note. Do not add outside facts unless the user explicitly asks for them.",
			"",
			"Output: Use short headings, bullets, and a final Remember this section."
		].join("\n")
	},
	{
		id: "question-drill",
		commandId: "workflow-question-drill",
		name: "Question Drill",
		shortName: "Drill",
		description: "Practice Qs",
		icon: "circle-help",
		accent: "amber",
		prompt: [
			"Goal: Turn the note context into an active-recall study drill.",
			"",
			"Success criteria:",
			"- Create questions that test the important ideas, not trivia.",
			"- Provide concise answers grounded in the note.",
			"- Include a few harder questions that require synthesis when the context supports it.",
			"- Flag any area where the note lacks enough detail for a fair question.",
			"",
			"Constraints: Do not invent answers. If evidence is thin, ask review questions instead of pretending certainty.",
			"",
			"Output: Use an Obsidian Markdown table with Question, Answer, and Why it matters."
		].join("\n")
	},
	{
		id: "buyer-protection-analysis",
		commandId: "workflow-buyer-protection-analysis",
		name: "Buyer Protection Analysis",
		shortName: "Protect",
		description: "Spot hype",
		icon: "shield-alert",
		accent: "rose",
		prompt: [
			"Goal: Judge whether the note, transcript, or sales-style content gives practical value or mainly creates desire, fear, curiosity, or pressure to buy, follow, join, or pay.",
			"",
			"Success criteria:",
			"- Give a direct verdict and buyer caution level: Low, Medium, High, or Very High.",
			"- Separate useful takeaways from vague motivation or unsupported claims.",
			"- Identify persuasion tactics, missing proof, risks, and red flags.",
			"- Explain the safest practical next step for the user.",
			"",
			"Constraints: Use British English. Be fair, sceptical, and evidence-based. Treat income claims, case studies, screenshots, shortcuts, and success stories as unverified unless the context proves them.",
			"",
			"Output: Use Obsidian Markdown with Direct verdict, Useful takeaways, Persuasion tactics, Red flags, Missing evidence, and What to do next."
		].join("\n")
	},
	{
		id: "knowledge-graph-links",
		commandId: "workflow-knowledge-graph-links",
		name: "Knowledge Graph Links",
		shortName: "Links",
		description: "Suggest [[links]]",
		icon: "network",
		accent: "violet",
		prompt: [
			"Goal: Analyse the note or selected text and generate useful Obsidian wikilinks for the knowledge graph.",
			"",
			"Context: In Obsidian, text wrapped in double square brackets, such as [[Concept]], creates an internal note link. These links can connect notes in the graph view. The user wants high-signal [[wikilinks]], not generic hashtags.",
			"",
			"Success criteria:",
			"- Suggest 8 to 15 high-value wikilinks that would genuinely improve knowledge graph connections.",
			"- Prefer named people, companies, tools, frameworks, skills, business models, problems, methods, recurring concepts, and decision themes.",
			"- Use clean note-style names, for example [[Customer Acquisition]], [[Online Education]], or [[Offer Design]].",
			"- Use an alias only when the phrase in the note is messy but should point to a cleaner note name, for example [[Customer Acquisition|finding customers]].",
			"- Explain briefly why each link matters and where it could be used.",
			"",
			"Constraints:",
			"- Do not overlink.",
			"- Do not suggest vague links like [[Thing]], [[People]], [[Video]], [[Success]], [[Business]], or [[Money]] unless the note gives a precise reason.",
			"- Do not invent facts outside the note.",
			"- If the note is too thin, say that and suggest fewer links.",
			"- Use British English.",
			"",
			"Output format:",
			"",
			"### Suggested Obsidian links",
			"",
			"| Wikilink | Why it matters | Suggested use |",
			"|---|---|---|",
			"",
			"### Copy-ready link block",
			"",
			"Return a compact block of the best links, one per line, ready to copy into an Obsidian note.",
			"",
			"### Inline linking suggestions",
			"",
			"Give 3 to 6 examples of exact phrases from the note and how to convert them into wikilinks.",
			"",
			"### Link hygiene",
			"",
			"End with any cautions about links that are too broad, duplicated, or not worth creating."
		].join("\n")
	},

	{
		id: "mermaid-diagram",
		commandId: "workflow-mermaid-diagram",
		name: "Mermaid Diagram",
		shortName: "Diagram",
		description: "Visual map",
		icon: "workflow",
		accent: "blue",
		prompt: [
			"Goal: Generate a valid Mermaid diagram that visualises the provided note or selection.",
			"",
			"Success criteria:",
			"- Choose the Mermaid diagram type that best fits the context, such as flowchart, mindmap, sequenceDiagram, timeline, journey, or classDiagram.",
			"- Represent the main entities, steps, decisions, relationships, causes, or timeline from the note.",
			"- Keep labels short, readable, and traceable to the note context.",
			"- Include important uncertainty or missing links as labelled nodes only when the note supports that gap.",
			"- Produce Mermaid syntax that should render in Obsidian without extra cleanup.",
			"",
			"Constraints:",
			"- Use only the provided note context. Do not add outside facts or invented relationships.",
			"- Prefer a simple diagram over a crowded one. If the note is thin, create a small diagram and mention what evidence is missing.",
			"- Escape or simplify labels that could break Mermaid syntax, including quotes, pipes, brackets, and Markdown links.",
			"- Do not include analysis, implementation notes, or alternative diagrams unless needed because the context is ambiguous.",
			"",
			"Output: Return one Obsidian Markdown fenced code block with language mermaid. Add a brief note after the block only if evidence is too thin or an assumption is necessary.",
			"",
			"Stop rules: Stop after the Mermaid block and any brief evidence note. Do not include process."
		].join("\n")
	},
	{
		id: "key-insights",
		commandId: "workflow-key-insights",
		name: "Key Insights",
		shortName: "Insights",
		description: "Best ideas",
		icon: "lightbulb",
		accent: "amber",
		prompt: [
			"Goal: Extract the most useful insights from the note or selection.",
			"",
			"Success criteria:",
			"- Identify the strongest ideas, patterns, claims, and implications.",
			"- Separate obvious points from genuinely useful insights.",
			"- Include supporting evidence from the note when available.",
			"- Say what is uncertain or missing if the note does not support a claim.",
			"",
			"Constraints: Stay grounded in the note context. Do not add outside facts.",
			"",
			"Output: Use Obsidian Markdown with Key insights, Evidence, and Why it matters."
		].join("\n")
	},
	{
		id: "critical-review",
		commandId: "workflow-critical-review",
		name: "Critical Review",
		shortName: "Critique",
		description: "Find gaps",
		icon: "search",
		accent: "rose",
		prompt: [
			"Goal: Critically review the note or selection for weak reasoning, missing evidence, and unclear claims.",
			"",
			"Success criteria:",
			"- Identify the main claims being made.",
			"- Point out unsupported claims, vague language, contradictions, and missing assumptions.",
			"- Separate serious problems from minor improvements.",
			"- Suggest practical fixes or questions to answer next.",
			"",
			"Constraints: Be fair and specific. Use only the note context and label uncertainty clearly.",
			"",
			"Output: Use sections for Strong points, Weak points, Missing evidence, and Fix next."
		].join("\n")
	},
	{
		id: "pros-cons",
		commandId: "workflow-pros-cons",
		name: "Pros And Cons",
		shortName: "Pros/Cons",
		description: "Weigh it up",
		icon: "scale",
		accent: "slate",
		prompt: [
			"Goal: Turn the note context into a balanced pros and cons analysis.",
			"",
			"Success criteria:",
			"- State the decision, idea, offer, or position being evaluated.",
			"- List the strongest pros and cons supported by the context.",
			"- Add risks, trade-offs, and unknowns that matter.",
			"- Give a careful recommendation only if the evidence supports one.",
			"",
			"Constraints: Do not invent missing context. If the note is one-sided, say so.",
			"",
			"Output: Use an Obsidian Markdown table plus a short recommendation."
		].join("\n")
	},
	{
		id: "flashcards",
		commandId: "workflow-flashcards",
		name: "Flashcards",
		shortName: "Cards",
		description: "Study cards",
		icon: "copy-check",
		accent: "blue",
		prompt: [
			"Goal: Create useful flashcards from the note or selection.",
			"",
			"Success criteria:",
			"- Create cards for key concepts, facts, definitions, decisions, and examples.",
			"- Keep each answer short enough to memorise.",
			"- Avoid trivial questions and duplicated cards.",
			"- Include uncertainty only when the note is unclear.",
			"",
			"Constraints: Use only the note context. Do not invent answers.",
			"",
			"Output: Use a Markdown table with Front, Back, and Source clue."
		].join("\n")
	},
	{
		id: "meeting-notes",
		commandId: "workflow-meeting-notes",
		name: "Meeting Notes",
		shortName: "Meeting",
		description: "Clean notes",
		icon: "messages-square",
		accent: "green",
		prompt: [
			"Goal: Convert rough meeting notes, call notes, or transcript snippets into clean meeting notes.",
			"",
			"Success criteria:",
			"- Identify decisions, action items, owners, deadlines, blockers, and open questions when present.",
			"- Keep discussion notes concise and grouped by topic.",
			"- Preserve names, dates, numbers, and commitments from the context.",
			"- Mark missing owners or deadlines clearly.",
			"",
			"Constraints: Do not invent commitments, attendees, or decisions.",
			"",
			"Output: Use sections for Summary, Decisions, Actions, Risks, and Open questions."
		].join("\n")
	},
	{
		id: "research-map",
		commandId: "workflow-research-map",
		name: "Research Map",
		shortName: "Research",
		description: "Explore next",
		icon: "compass",
		accent: "violet",
		prompt: [
			"Goal: Create a research map from the note context so the user knows what to investigate next.",
			"",
			"Success criteria:",
			"- Identify the central topic and its subtopics.",
			"- List important unanswered questions.",
			"- Suggest search terms, source types, and evidence to look for.",
			"- Prioritise the highest-leverage next research steps.",
			"",
			"Constraints: Do not pretend to have researched outside the note. Clearly label this as a plan based on current context.",
			"",
			"Output: Use Obsidian Markdown with Topic map, Questions, Evidence needed, and Next searches."
		].join("\n")
	},
	{
		id: "decision-brief",
		commandId: "workflow-decision-brief",
		name: "Decision Brief",
		shortName: "Decision",
		description: "Choose well",
		icon: "file-question",
		accent: "amber",
		prompt: [
			"Goal: Turn the note context into a decision brief.",
			"",
			"Success criteria:",
			"- State the decision to be made.",
			"- Summarise the available evidence, options, trade-offs, and risks.",
			"- Identify what information is still missing before deciding.",
			"- Recommend the next best decision step, not a fake final answer if evidence is insufficient.",
			"",
			"Constraints: Keep advice grounded in the note. Mark assumptions clearly.",
			"",
			"Output: Use sections for Decision, Evidence, Options, Risks, Missing information, and Next step."
		].join("\n")
	},
	{
		id: "compare-ideas",
		commandId: "workflow-compare-ideas",
		name: "Compare Ideas",
		shortName: "Compare",
		description: "Contrast ideas",
		icon: "git-compare",
		accent: "blue",
		prompt: [
			"Goal: Compare the main ideas, options, people, tools, methods, or arguments in the note context.",
			"",
			"Success criteria:",
			"- Identify what is being compared.",
			"- Explain similarities, differences, strengths, weaknesses, and use cases.",
			"- Include evidence from the note where possible.",
			"- Say when the context does not provide enough information for a fair comparison.",
			"",
			"Constraints: Do not add outside facts unless the user asks for them.",
			"",
			"Output: Use a Markdown comparison table plus a short takeaway."
		].join("\n")
	},
	{
		id: "translate-preserve",
		commandId: "workflow-translate-preserve",
		name: "Translate Preserve",
		shortName: "Translate",
		description: "Keep meaning",
		icon: "languages",
		accent: "green",
		prompt: (settings) => buildTranslatePreservePrompt(settings.translationTargetLanguage)
	},
	{
		id: "quote-extractor",
		commandId: "workflow-quote-extractor",
		name: "Quote Extractor",
		shortName: "Quotes",
		description: "Pull quotes",
		icon: "quote",
		accent: "rose",
		prompt: [
			"Goal: Extract the strongest quotes, claims, examples, numbers, and memorable lines from the note context.",
			"",
			"Success criteria:",
			"- Select only lines or claims that are useful, specific, or worth referencing later.",
			"- Keep wording exact when quoting and avoid over-quoting weak lines.",
			"- Explain briefly why each item matters.",
			"- Flag unsupported or questionable claims separately.",
			"",
			"Constraints: Do not invent quotes. If exact wording is not available, label it as a paraphrase.",
			"",
			"Output: Use sections for Best quotes, Key claims, Useful examples, Numbers, and Cautions."
		].join("\n")
	},

	{
		id: "rewrite-polish",
		commandId: "workflow-rewrite-polish",
		name: "Rewrite Polish",
		shortName: "Polish",
		description: "Clean rewrite",
		icon: "wand-2",
		accent: "slate",
		prompt: [
			"Goal: Rewrite the note or selection into clearer, more polished Obsidian Markdown.",
			"",
			"Success criteria:",
			"- Preserve the original meaning, names, numbers, dates, and important structure.",
			"- Improve clarity, flow, headings, bullets, and readability.",
			"- Keep uncertainty, caveats, and missing information visible.",
			"- Remove repetition without removing important evidence.",
			"",
			"Constraints: Do not add new facts. If the source is fragmented, tidy it while keeping that limitation clear.",
			"",
			"Output: Return only the polished Markdown, ready to paste into Obsidian."
		].join("\n")
	}
];
