import { DEFAULT_ADDITIONAL_CONTEXT_MAX_CHARACTERS, DEFAULT_BATCH_WORKFLOW_MAX_FILES, DEFAULT_EVIDENCE_MAX_SOURCES, DEFAULT_EXCALIDRAW_SUMMARY_MAX_CHARACTERS, DEFAULT_FOLDER_CONTEXT_MAX_CHARACTERS, DEFAULT_FOLDER_CONTEXT_MAX_FILES, DEFAULT_IMAGE_FILE_NAME_TEMPLATE, DEFAULT_IMAGE_FOLDER_TEMPLATE, DEFAULT_IMAGE_RESULT_NOTE_TEMPLATE, DEFAULT_MODEL_OPTIONS, DEFAULT_NOTE_HISTORY_MAX_TURNS_PER_NOTE, DEFAULT_PROVIDER_ROLE_SETTINGS, DEFAULT_PROVIDER_SETTINGS, DEFAULT_REASONING_EFFORT, DEFAULT_REQUEST_PRIVACY_OPTIONS, DEFAULT_RESULT_NOTE_TEMPLATE, DEFAULT_REVIEW_QUEUE_MAX_ITEMS, DEFAULT_ROLE_CONTEXT_MAX_CHARACTERS, DEFAULT_SEND_SHORTCUT, DEFAULT_THREADED_CHAT_MAX_TURNS, DEFAULT_TRANSLATION_TARGET_LANGUAGE, DEFAULT_USAGE_PER_REQUEST_WARNING_TOKENS } from "./constants";
import type { AskMateSettings } from "../shared/types";

export const DEFAULT_SETTINGS: AskMateSettings = {
	openAiApiKeySecretName: "",
	model: "gpt-5.5",
	modelOptions: DEFAULT_MODEL_OPTIONS,
	selectedTextProvider: "openai",
	providerRoles: DEFAULT_PROVIDER_ROLE_SETTINGS,
	providers: DEFAULT_PROVIDER_SETTINGS,
	customWorkflows: [],
	requestPrivacyDefaults: DEFAULT_REQUEST_PRIVACY_OPTIONS,
	contextBudgetMode: "expanded",
	workflowDisplayPreferences: [],
	showRequestPreview: true,
	applyApprovalMode: "manual",
	showApplyPreview: true,
	outputMode: "chat",
	reasoningEffort: DEFAULT_REASONING_EFFORT,
	sendShortcut: DEFAULT_SEND_SHORTCUT,
	resultFolder: "AskMate",
	resultNoteTemplate: DEFAULT_RESULT_NOTE_TEMPLATE,
	imageResultNoteTemplate: DEFAULT_IMAGE_RESULT_NOTE_TEMPLATE,
	imageFolderTemplate: DEFAULT_IMAGE_FOLDER_TEMPLATE,
	imageFileNameTemplate: DEFAULT_IMAGE_FILE_NAME_TEMPLATE,
	translationTargetLanguage: DEFAULT_TRANSLATION_TARGET_LANGUAGE,
	workflowCustomInstructions: "",
	composerLayout: "compact",
	showOnboardingTips: true,
	onboardingTipsDismissedAt: null,
	threadedChatEnabled: false,
	threadedChatMaxTurns: DEFAULT_THREADED_CHAT_MAX_TURNS,
	additionalContextPaths: [],
	additionalContextMaxCharacters: DEFAULT_ADDITIONAL_CONTEXT_MAX_CHARACTERS,
	folderContextEnabled: false,
	folderContextPath: "",
	folderContextMaxFiles: DEFAULT_FOLDER_CONTEXT_MAX_FILES,
	folderContextMaxCharacters: DEFAULT_FOLDER_CONTEXT_MAX_CHARACTERS,
	includeExcalidrawSummaries: false,
	excalidrawSummaryMaxCharacters: DEFAULT_EXCALIDRAW_SUMMARY_MAX_CHARACTERS,
	includeImageManifests: false,
	partialApplyDefaultScope: "auto",
	evidenceLinkedAnswersEnabled: true,
	evidenceMaxSources: DEFAULT_EVIDENCE_MAX_SOURCES,
	frontmatterApplyPolicy: "preserve",
	batchWorkflowFolderPath: "",
	batchWorkflowId: "study-summary",
	batchWorkflowMaxFiles: DEFAULT_BATCH_WORKFLOW_MAX_FILES,
	batchWorkflowOutputMode: "note",
	noteHistoryEnabled: true,
	noteHistoryIncludeInContext: false,
	noteHistoryMaxTurnsPerNote: DEFAULT_NOTE_HISTORY_MAX_TURNS_PER_NOTE,
	noteHistoryStore: { turns: [] },
	includeStyleGuideContext: false,
	styleGuideContextPath: "",
	styleGuideMaxCharacters: DEFAULT_ROLE_CONTEXT_MAX_CHARACTERS,
	includeGlossaryContext: false,
	glossaryContextPath: "",
	glossaryMaxCharacters: DEFAULT_ROLE_CONTEXT_MAX_CHARACTERS,
	reviewQueue: [],
	reviewQueueMaxItems: DEFAULT_REVIEW_QUEUE_MAX_ITEMS,
	smartResultPlacementEnabled: false,
	appendResultBacklinkToSource: false,
	usageGuardrailsEnabled: false,
	usageDailyTokenBudget: 0,
	usageMonthlyTokenBudget: 0,
	usagePerRequestWarningTokens: DEFAULT_USAGE_PER_REQUEST_WARNING_TOKENS,
	usagePerRequestHardLimitTokens: 0,
	usageBudgetEnforcement: "warn",
	tokenUsageStats: {
		records: []
	}
};
